- name: Enable extras repos
  shell: yum-config-manager --enable rhui-REGION-rhel-server-extras
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version|int < 8
    - instance_loc == 'ec2'

- name: Add Ansible repo - transition to engine...
  yum_repository:
    name: ansible
    description: Ansible for Enterprise Linux 7
    baseurl: http://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/
    enabled: yes
    gpgcheck: no
  when: ansible_distribution_major_version|int < 8

- name: Add Epel repo
  yum_repository:
    name: epel
    description: EPEL for Enterprise Linux 8
    baseurl: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/
    enabled: yes
    gpgcheck: no
  when: ansible_distribution_major_version|int == 8

- name: Install packages
  package:
    name:
      - vim
      - git
      - sshpass
      - ansible
      - nano
      - bind-utils
      - python-pip
    state: present
  when: ansible_distribution_major_version|int < 8

- name: Install packages
  package:
    name:
      - vim
      - git
      - nano
      - bind-utils
      - python36
    state: present
  when: ansible_distribution_major_version|int == 8

- name: install the last version of OpenSSL
  pip:
    name: pyOpenSSL
    state: latest

- name: Install dependencies for Kerberos auth
  package:
    name:
      - python-devel
      - krb5-devel
      - krb5-libs
      - krb5-workstation
      - python-kerberos
      - gcc
    state: present
  when: ansible_distribution_major_version|int < 8

- name: Install dependencies for Kerberos auth
  package:
    name:
      - krb5-devel
      - krb5-libs
      - krb5-workstation
      - gcc
    state: present
  when: ansible_distribution_major_version|int == 8

- name: Install pywinrm for connecting to windows hosts
  pip:
    name:
      - pywinrm>=0.2.2
      - pywinrm[kerberos]
      - pywinrm[credssp]

#- name: Install requests-credssp for Tower 3.2
#  pip:
#    name: requests-credssp
#  when: towerversion < 3.3

#- name: Configure KRB5.conf file
#  template:
#    src: krb5.conf.j2
#    dest: /etc/krb5.conf
#    owner: root
#    group: root
#    mode: 0644

- name: Install pywinrm for connecting to windows hosts
  pip:
    name:
      - urllib3
    state: absent

- name: Update all packages
  yum:
    name: "*"
    state: latest

- name: Clean Cache
  command: yum clean all
  args:
    warn: false

- include_tasks: install.yml
  when: inventory_hostname == name_prefix + "-tower-1"


