- name: Add EPEL repo for RHEL 7
  yum_repository:
    name: epel
    description: EPEL for Enterprise Linux 7
    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/
    enabled: yes
    gpgcheck: no
  when: ansible_distribution_major_version|int == 7

- name: Add EPEL repo for RHEL 8
  yum_repository:
    name: epel
    description: EPEL for Enterprise Linux 8
    baseurl: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/
    enabled: yes
    gpgcheck: no
  when: ansible_distribution_major_version|int == 8

- name: Enable optional repos for RHEL 7 (ec2)
  command: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version|int == 7
    - instance_loc == 'ec2'

- name: Enable appstream repo for RHEL 8 (non-ec2)
  command: yum-config-manager --enable rhel-8-for-x86_64-appstream-rpms
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version|int == 8
    - instance_loc != 'ec2'

- name: Install packages
  package:
    name:
      - vim
      - bind-utils
    state: present

- name: Modify /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
